---

- name: send apache2.conf
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
   - restart apache service
- name: send index.html
  copy: src=index.html dest=/var/www/html/index.html
